In [102]:
import pandas as pd

# import data
imdb = pd.read_csv('imdb_top_1000.csv')
imdb.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [98]:
# Data quality check
print(imdb.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB
None

In [104]:
# Convert Runtime into an integer column
runtime = imdb['Runtime'].str.replace('min', '').astype('int')

trans_runtime = imdb.assign( runtime_in_minutes = lambda df_: runtime)
trans_runtime

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,runtime_in_minutes
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469",142
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411",175
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444",152
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000",202
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000",96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,NaN,115
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,NaN,201
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000",118
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,NaN,97
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,NaN,86

In [105]:
# split movie genres in the Genre column
trans_runtime['Genre'] = trans_runtime['Genre'].str.split(', ')

In [106]:
processed = trans_runtime.explode('Genre')
# genre_processed['Series_Title', 'Released_Year', 'Genre', 'IMDB_Rating']

In [107]:
# combine all stars into one column

processed['All_Stars'] = processed[['Star1', 'Star2', 'Star3', 'Star4']].values.tolist()
star_processed = processed.explode('All_Stars')

In [108]:
star_processed.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10164 entries, 0 to 999
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Poster_Link         10164 non-null  object
 1   Series_Title        10164 non-null  object
 2   Released_Year       10164 non-null  object
 3   Certificate         9224 non-null   object
 4   Runtime             10164 non-null  object
 5   Genre               10164 non-null  object
 6   IMDB_Rating         10164 non-null  float64
 7   Overview            10164 non-null  object
 8   Meta_score          8584 non-null   float64
 9   Director            10164 non-null  object
 10  Star1               10164 non-null  object
 11  Star2               10164 non-null  object
 12  Star3               10164 non-null  object
 13  Star4               10164 non-null  object
 14  No_of_Votes         10164 non-null  int64
 15  Gross               8436 non-null   object
 16  runtime_in_minutes  10164 non-null  int64
 17  All_Stars           10164 non-null  object
dtypes: float64(2), int64(2), object(14)
memory usage: 1.5+ MB

In [109]:
exporting_columns = ['Series_Title', 
                     'Released_Year', 
                     'Certificate', 
                     'Genre', 
                     'All_Stars',
                     'runtime_in_minutes',
                     'IMDB_Rating', 
                     'Meta_score', 
                     'Director',
                     'No_of_Votes',
                     'Gross'
                    ]
export = star_processed[exporting_columns]
export

,Series_Title,Released_Year,Certificate,Genre,All_Stars,runtime_in_minutes,IMDB_Rating,Meta_score,Director,No_of_Votes,Gross
0,The Shawshank Redemption,1994,A,Drama,Tim Robbins,142,9.3,80.0,Frank Darabont,2343110,"28,341,469"
0,The Shawshank Redemption,1994,A,Drama,Morgan Freeman,142,9.3,80.0,Frank Darabont,2343110,"28,341,469"
0,The Shawshank Redemption,1994,A,Drama,Bob Gunton,142,9.3,80.0,Frank Darabont,2343110,"28,341,469"
0,The Shawshank Redemption,1994,A,Drama,William Sadler,142,9.3,80.0,Frank Darabont,2343110,"28,341,469"
1,The Godfather,1972,A,Crime,Marlon Brando,175,9.2,100.0,Francis Ford Coppola,1620367,"134,966,411"
...,...,...,...,...,...,...,...,...,...,...,...
999,The 39 Steps,1935,NaN,Mystery,Godfrey Tearle,86,7.6,93.0,Alfred Hitchcock,51853,NaN
999,The 39 Steps,1935,NaN,Thriller,Robert Donat,86,7.6,93.0,Alfred Hitchcock,51853,NaN
999,The 39 Steps,1935,NaN,Thriller,Madeleine Carroll,86,7.6,93.0,Alfred Hitchcock,51853,NaN
999,The 39 Steps,1935,NaN,Thriller,Lucie Mannheim,86,7.6,93.0,Alfred Hitchcock,51853,NaN
999,The 39 Steps,1935,NaN,Thriller,Godfrey Tearle,86,7.6,93.0,Alfred Hitchcock,51853,NaN

In [110]:
# export data
export.to_csv('IMDB_top_1000_flatten.csv')